springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: 'tiny-honey'
      paths-to-match: '/**'
      packages-to-scan: com.kmosi.api
knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: false
    enableDocumentManage: false
    enable-version: true
    enable-after-script: false
    enable-open-api: false
    enable-group: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2023-[XXX科技股份有限公司](http://127.0.0.1)